spring:
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "1"
          keystore:
            location: "classpath:bank-server-keystore.p12"
            password: "1234"
            type: "PKCS12"
          truststore:
            location: "classpath:truststore.jks"
            password: "123456"
server:
  ssl:
    bundle: "server"
    client-auth: NEED
  port: 8443
