spring:
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "1"
          keystore:
            location: "classpath:openssl/bundles/bank-server-keystore.p12"
            password: "1234"
            type: "PKCS12"
      # pem:
      #   client:
      #     truststore:
      #       certificate: "classpath:client.crt"
server:
  ssl:
    bundle: "server"
    # client-auth: NEED
  port: 8443
